import 'package:flutter/material.dart';

import '../../theme/world_profile.dart';
import 'world_presentation_pack.dart';

/// 8 世界観のプレゼンテーションパック。
abstract final class WorldPresentationCatalog {
  static WorldPresentationPack of(WorldProfile profile) =>
      _all[profile] ?? _all[WorldProfile.horror]!;

  static const _all = <WorldProfile, WorldPresentationPack>{
    WorldProfile.horror: WorldPresentationPack(
      profile: WorldProfile.horror,
      tagline: '深夜都市の調査ファイル',
      shortIntro: '監視・VHS・静かなホラー。スタイリッシュな事件現場。',
      headlineFont: 'Special Elite',
      bodyFont: 'IBM Plex Sans JP',
      headlineLetterSpacing: 1.8,
      bodyLetterSpacing: 0.2,
      headlineWeight: FontWeight.w600,
      bodyLineHeight: 1.45,
      scaffoldTop: Color(0xFF0E1114),
      scaffoldBottom: Color(0xFF151A1F),
      panelSurface: Color(0xE6151A1F),
      panelBorder: Color(0x448FA3B5),
      accent: Color(0xFF8FA3B5),
      accentMuted: Color(0xFF7B8794),
      onAccent: Color(0xFFE5E8EA),
      successColor: Color(0xFF2E4A3E),
      dangerColor: Color(0xFF6D4C4F),
      warningColor: Color(0xFF5D4037),
      profileIcon: Icons.nightlight_round,
      decorSymbol: '▮',
      buttonShape: WorldButtonShape(
        borderRadius: 4,
        borderWidth: 1,
        elevation: 0,
        pressScale: 0.98,
        outlined: true,
      ),
      loadingKind: WorldLoadingKind.horrorTape,
      pinSilhouette: WorldPinSilhouette.angular,
      momentParticle: WorldParticleKind.smokeRain,
      flashKind: WorldFlashKind.vhsFlicker,
      winAccent: Color(0xFF78909C),
      loseAccent: Color(0xFF4A148C),
      resultHeadlineWin: 'CASE CLOSED',
      resultHeadlineLose: 'FILE LOST',
      chipBorderRadius: 4,
      hudCornerRadius: 6,
    ),
    WorldProfile.sport: WorldPresentationPack(
      profile: WorldProfile.sport,
      tagline: '休日の街を駆け抜けよう',
      shortIntro: 'ネオン・丸み・軽快。Zenly 的なポップな週末。',
      headlineFont: 'Nunito',
      bodyFont: 'M PLUS Rounded 1c',
      headlineLetterSpacing: 0.6,
      bodyLetterSpacing: 0.1,
      headlineWeight: FontWeight.w800,
      bodyLineHeight: 1.4,
      scaffoldTop: Color(0xFFFFF7E8),
      scaffoldBottom: Color(0xFFFFF0F5),
      panelSurface: Color(0xF8FFFFFF),
      panelBorder: Color(0x66253047),
      accent: Color(0xFFFF6FAE),
      accentMuted: Color(0xFF6ECFFF),
      onAccent: Color(0xFFFFFFFF),
      successColor: Color(0xFF00C853),
      dangerColor: Color(0xFFFF6D00),
      warningColor: Color(0xFFFFD600),
      profileIcon: Icons.wb_sunny_outlined,
      decorSymbol: '◎',
      buttonShape: WorldButtonShape(
        borderRadius: 28,
        elevation: 4,
        pressScale: 0.94,
        useGradient: true,
      ),
      loadingKind: WorldLoadingKind.popBounce,
      pinSilhouette: WorldPinSilhouette.rounded,
      momentParticle: WorldParticleKind.neonPop,
      flashKind: WorldFlashKind.popBurst,
      winAccent: Color(0xFF00E676),
      loseAccent: Color(0xFFFF3D00),
      resultHeadlineWin: 'YOU WIN!',
      resultHeadlineLose: 'TRY AGAIN',
      chipBorderRadius: 20,
      hudCornerRadius: 18,
    ),
    WorldProfile.sciFi: WorldPresentationPack(
      profile: WorldProfile.sciFi,
      tagline: '電子都市への侵入',
      shortIntro: 'TRON × 攻殻。UI が世界そのもの。',
      headlineFont: 'Orbitron',
      bodyFont: 'Share Tech Mono',
      headlineLetterSpacing: 2.4,
      bodyLetterSpacing: 0.4,
      headlineWeight: FontWeight.w700,
      bodyLineHeight: 1.35,
      scaffoldTop: Color(0xFF05070D),
      scaffoldBottom: Color(0xFF0D1220),
      panelSurface: Color(0xE60D1220),
      panelBorder: Color(0x6600F0FF),
      accent: Color(0xFF00F0FF),
      accentMuted: Color(0xFF7A3CFF),
      onAccent: Color(0xFFEAFBFF),
      successColor: Color(0xFF00BFA5),
      dangerColor: Color(0xFFFF1744),
      warningColor: Color(0xFFFF9100),
      profileIcon: Icons.hub_outlined,
      decorSymbol: '⟨⟩',
      buttonShape: WorldButtonShape(
        borderRadius: 2,
        borderWidth: 1.5,
        elevation: 0,
        pressScale: 0.96,
        outlined: true,
      ),
      loadingKind: WorldLoadingKind.cyberPulse,
      pinSilhouette: WorldPinSilhouette.hex,
      momentParticle: WorldParticleKind.dataBits,
      flashKind: WorldFlashKind.cyberGlitch,
      winAccent: Color(0xFF18FFFF),
      loseAccent: Color(0xFFFF1744),
      resultHeadlineWin: 'SYSTEM COMPLETE',
      resultHeadlineLose: 'ACCESS LOST',
      chipBorderRadius: 2,
      hudCornerRadius: 4,
    ),
    WorldProfile.arg: WorldPresentationPack(
      profile: WorldProfile.arg,
      tagline: '夜間任務・通信管制下',
      shortIntro: 'MGS / Splinter Cell。実用品のような UI。',
      headlineFont: 'Barlow Condensed',
      bodyFont: 'IBM Plex Sans JP',
      headlineLetterSpacing: 1.2,
      bodyLetterSpacing: 0.15,
      headlineWeight: FontWeight.w700,
      bodyLineHeight: 1.4,
      scaffoldTop: Color(0xFF0B0D0B),
      scaffoldBottom: Color(0xFF151812),
      panelSurface: Color(0xE6151812),
      panelBorder: Color(0x446F7A45),
      accent: Color(0xFFD9DFD0),
      accentMuted: Color(0xFF7A8270),
      onAccent: Color(0xFFD9DFD0),
      successColor: Color(0xFF558B2F),
      dangerColor: Color(0xFF5D4037),
      warningColor: Color(0xFF6D4C41),
      profileIcon: Icons.visibility_off_outlined,
      decorSymbol: '▣',
      buttonShape: WorldButtonShape(
        borderRadius: 3,
        borderWidth: 1,
        elevation: 0,
        pressScale: 0.98,
      ),
      loadingKind: WorldLoadingKind.tacticalGrid,
      pinSilhouette: WorldPinSilhouette.angular,
      momentParticle: WorldParticleKind.dust,
      flashKind: WorldFlashKind.tacticalScan,
      winAccent: Color(0xFF689F38),
      loseAccent: Color(0xFF4E342E),
      resultHeadlineWin: 'MISSION COMPLETE',
      resultHeadlineLose: 'SIGNAL LOST',
      chipBorderRadius: 3,
      hudCornerRadius: 4,
    ),
    WorldProfile.magical: WorldPresentationPack(
      profile: WorldProfile.magical,
      tagline: '理論魔法・古代幾何学',
      shortIntro: '京都ではなく知的な神秘学。魔法陣と古代文字。',
      headlineFont: 'Cinzel',
      bodyFont: 'Cormorant Garamond',
      headlineLetterSpacing: 1.6,
      bodyLetterSpacing: 0.3,
      headlineWeight: FontWeight.w600,
      bodyLineHeight: 1.5,
      scaffoldTop: Color(0xFF110B1F),
      scaffoldBottom: Color(0xFF211538),
      panelSurface: Color(0xE6211538),
      panelBorder: Color(0x5544E5FF),
      accent: Color(0xFF7A3CFF),
      accentMuted: Color(0xFF44E5FF),
      onAccent: Color(0xFFF4EEFF),
      successColor: Color(0xFFAB47BC),
      dangerColor: Color(0xFFFF7043),
      warningColor: Color(0xFFFFD54F),
      profileIcon: Icons.auto_awesome,
      decorSymbol: '✦',
      buttonShape: WorldButtonShape(
        borderRadius: 12,
        borderWidth: 1,
        elevation: 2,
        pressScale: 0.96,
        useGradient: true,
      ),
      loadingKind: WorldLoadingKind.magicalSigil,
      pinSilhouette: WorldPinSilhouette.sigil,
      momentParticle: WorldParticleKind.sparks,
      flashKind: WorldFlashKind.sigilPulse,
      winAccent: Color(0xFF44E5FF),
      loseAccent: Color(0xFFFF8A3D),
      resultHeadlineWin: 'ARCANA COMPLETE',
      resultHeadlineLose: 'SIGIL BROKEN',
      chipBorderRadius: 12,
      hudCornerRadius: 10,
    ),
    WorldProfile.astronomy: WorldPresentationPack(
      profile: WorldProfile.astronomy,
      tagline: '宇宙への憧憬',
      shortIntro: 'Interstellar / Arrival。静寂と希望のリアル SF。',
      headlineFont: 'Exo 2',
      bodyFont: 'IBM Plex Sans JP',
      headlineLetterSpacing: 1.4,
      bodyLetterSpacing: 0.2,
      headlineWeight: FontWeight.w300,
      bodyLineHeight: 1.5,
      scaffoldTop: Color(0xFF02040A),
      scaffoldBottom: Color(0xFF07101F),
      panelSurface: Color(0xE607101F),
      panelBorder: Color(0x4477D7FF),
      accent: Color(0xFF77D7FF),
      accentMuted: Color(0xFF1F6FEB),
      onAccent: Color(0xFFE6F3FF),
      successColor: Color(0xFF5C6BC0),
      dangerColor: Color(0xFFFF6F00),
      warningColor: Color(0xFFFFB300),
      profileIcon: Icons.public,
      decorSymbol: '✧',
      buttonShape: WorldButtonShape(
        borderRadius: 8,
        borderWidth: 0.5,
        elevation: 0,
        pressScale: 0.97,
        outlined: true,
      ),
      loadingKind: WorldLoadingKind.astronomyOrbit,
      pinSilhouette: WorldPinSilhouette.orbit,
      momentParticle: WorldParticleKind.stardust,
      flashKind: WorldFlashKind.cosmicWave,
      winAccent: Color(0xFF4DD0E1),
      loseAccent: Color(0xFFFF8F00),
      resultHeadlineWin: 'SIGNAL HOME',
      resultHeadlineLose: 'LOST IN VOID',
      chipBorderRadius: 8,
      hudCornerRadius: 8,
    ),
    WorldProfile.japaneseLuxury: WorldPresentationPack(
      profile: WorldProfile.japaneseLuxury,
      tagline: '墨・間・静けさ',
      shortIntro: '禅・京都・和紙・漆。魔法ではない高級和風。',
      headlineFont: 'Noto Serif JP',
      bodyFont: 'Noto Sans JP',
      headlineLetterSpacing: 0.8,
      bodyLetterSpacing: 0.05,
      headlineWeight: FontWeight.w500,
      bodyLineHeight: 1.65,
      scaffoldTop: Color(0xFF12110E),
      scaffoldBottom: Color(0xFF1B1B18),
      panelSurface: Color(0xE6F2EBDD),
      panelBorder: Color(0x44A88445),
      accent: Color(0xFFA88445),
      accentMuted: Color(0xFF2E4A5F),
      onAccent: Color(0xFF2C2923),
      successColor: Color(0xFF2E4036),
      dangerColor: Color(0xFF5C4038),
      warningColor: Color(0xFF6D5B4B),
      profileIcon: Icons.temple_buddhist_outlined,
      decorSymbol: '墨',
      buttonShape: WorldButtonShape(
        borderRadius: 2,
        borderWidth: 1,
        elevation: 0,
        pressScale: 0.98,
        outlined: true,
      ),
      loadingKind: WorldLoadingKind.zenBrush,
      pinSilhouette: WorldPinSilhouette.inkDrop,
      momentParticle: WorldParticleKind.goldInk,
      flashKind: WorldFlashKind.inkWash,
      winAccent: Color(0xFFC9A227),
      loseAccent: Color(0xFF4A3728),
      resultHeadlineWin: '静寂の勝ち',
      resultHeadlineLose: '影に沈む',
      chipBorderRadius: 2,
      hudCornerRadius: 2,
    ),
    WorldProfile.westernLuxury: WorldPresentationPack(
      profile: WorldProfile.westernLuxury,
      tagline: '宮廷と大理石の格式',
      shortIntro: 'ヨーロッパ高級路線。金・白・大聖堂。',
      headlineFont: 'Playfair Display',
      bodyFont: 'Lora',
      headlineLetterSpacing: 0.5,
      bodyLetterSpacing: 0.15,
      headlineWeight: FontWeight.w600,
      bodyLineHeight: 1.55,
      scaffoldTop: Color(0xFFF6F1E7),
      scaffoldBottom: Color(0xFFFFFDF8),
      panelSurface: Color(0xF5FFFDF8),
      panelBorder: Color(0x55D4AF37),
      accent: Color(0xFFD4AF37),
      accentMuted: Color(0xFF6D2138),
      onAccent: Color(0xFF1E1A17),
      successColor: Color(0xFF2E7D32),
      dangerColor: Color(0xFF722F37),
      warningColor: Color(0xFF8D6E63),
      profileIcon: Icons.account_balance_outlined,
      decorSymbol: '♛',
      buttonShape: WorldButtonShape(
        borderRadius: 6,
        borderWidth: 1.5,
        elevation: 3,
        pressScale: 0.97,
        useGradient: true,
      ),
      loadingKind: WorldLoadingKind.royalSeal,
      pinSilhouette: WorldPinSilhouette.crest,
      momentParticle: WorldParticleKind.lightRays,
      flashKind: WorldFlashKind.gildedCurtain,
      winAccent: Color(0xFFD4AF37),
      loseAccent: Color(0xFF5D1A24),
      resultHeadlineWin: 'VERDICT',
      resultHeadlineLose: 'DISMISSED',
      chipBorderRadius: 6,
      hudCornerRadius: 6,
    ),
  };
}
