import 'package:flutter/material.dart';

import '../../theme/world_profile.dart';
import 'world_studio_identity.dart';

/// 8 スタジオ人格の定義。
abstract final class WorldStudioIdentityCatalog {
  static WorldStudioIdentity of(WorldProfile profile) =>
      _all[profile] ?? _all[WorldProfile.horror]!;

  static Iterable<WorldStudioIdentity> get all => _all.values;

  static const _all = <WorldProfile, WorldStudioIdentity>{
    WorldProfile.horror: WorldStudioIdentity(
      profile: WorldProfile.horror,
      layout: WorldLayoutRhythm(
        screenPaddingH: 22,
        screenPaddingV: 20,
        sectionGap: 22,
        cardGap: 14,
        dialogPaddingH: 20,
        symmetric: false,
        contentAlign: Alignment.centerLeft,
        cardFloat: 0,
        hudEdgeInset: 8,
        galleryHeroHeight: 0.34,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 520,
        reverseTransitionMs: 420,
        dialogMs: 380,
        buttonMs: 140,
        staggerMs: 90,
        enterCurve: Curves.easeInOutCubic,
        exitCurve: Curves.easeInCubic,
        emphasisCurve: Curves.easeInOut,
        sheetCurve: Curves.easeOutCubic,
      ),
      microcopy: WorldMicrocopy(
        confirm: '調査を続ける',
        cancel: '保留',
        close: 'ファイルを閉じる',
        next: '次の手がかり',
        back: '戻る',
        loading: '確認中…',
        gallerySelect: 'Open Case',
        coachNext: '次へ',
        coachDone: '始める',
      ),
      haptic: WorldHapticCharacter.heavy,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 40,
        sfxTailMs: 120,
        transitionBreathMs: 80,
        resultPauseMs: 280,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 38,
        zoomOffset: 0.2,
        orbitScale: 0.5,
        shotDelayMs: 980,
        initialDelayMs: 620,
        bearingSpread: 1.0,
      ),
      resultCopy: WorldResultCopy(
        win: 'CASE CLOSED',
        lose: 'CASE OPEN',
        draw: 'UNRESOLVED',
        spectator: 'OBSERVATION LOG',
        abort: 'INVESTIGATION HALTED',
      ),
    ),
    WorldProfile.sport: WorldStudioIdentity(
      profile: WorldProfile.sport,
      layout: WorldLayoutRhythm(
        screenPaddingH: 16,
        screenPaddingV: 14,
        sectionGap: 12,
        cardGap: 10,
        dialogPaddingH: 16,
        symmetric: true,
        contentAlign: Alignment.center,
        cardFloat: 6,
        hudEdgeInset: 10,
        galleryHeroHeight: 0.38,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 280,
        reverseTransitionMs: 220,
        dialogMs: 260,
        buttonMs: 90,
        staggerMs: 40,
        enterCurve: Curves.elasticOut,
        exitCurve: Curves.easeIn,
        emphasisCurve: Curves.bounceOut,
        sheetCurve: Curves.easeOutBack,
      ),
      microcopy: WorldMicrocopy(
        confirm: 'いくよ！',
        cancel: 'まだ',
        close: '閉じる',
        next: '次へ！',
        back: '戻る',
        loading: '準備中…',
        gallerySelect: 'Pick this vibe',
        coachNext: '次へ！',
        coachDone: 'スタート！',
      ),
      haptic: WorldHapticCharacter.pulse,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 0,
        sfxTailMs: 40,
        transitionBreathMs: 20,
        resultPauseMs: 120,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 28,
        zoomOffset: 0.8,
        orbitScale: 0.62,
        shotDelayMs: 620,
        initialDelayMs: 380,
        bearingSpread: 1.1,
      ),
      resultCopy: WorldResultCopy(
        win: 'NICE RUN!',
        lose: 'CAUGHT!',
        draw: 'TIME!',
        spectator: 'WATCH PARTY',
        abort: 'GAME PAUSED',
      ),
    ),
    WorldProfile.sciFi: WorldStudioIdentity(
      profile: WorldProfile.sciFi,
      layout: WorldLayoutRhythm(
        screenPaddingH: 14,
        screenPaddingV: 12,
        sectionGap: 10,
        cardGap: 8,
        dialogPaddingH: 12,
        symmetric: true,
        contentAlign: Alignment.topCenter,
        cardFloat: 2,
        hudEdgeInset: 6,
        galleryHeroHeight: 0.32,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 220,
        reverseTransitionMs: 180,
        dialogMs: 200,
        buttonMs: 70,
        staggerMs: 30,
        enterCurve: Curves.easeOutQuart,
        exitCurve: Curves.easeInQuart,
        emphasisCurve: Curves.easeOutExpo,
        sheetCurve: Curves.easeOutCubic,
      ),
      microcopy: WorldMicrocopy(
        confirm: '実行',
        cancel: '中断',
        close: '切断',
        next: '次へ',
        back: '戻る',
        loading: '同期中…',
        gallerySelect: 'Jack In',
        coachNext: '次へ',
        coachDone: '開始',
      ),
      haptic: WorldHapticCharacter.click,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 12,
        sfxTailMs: 60,
        transitionBreathMs: 30,
        resultPauseMs: 160,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 52,
        zoomOffset: 0.9,
        orbitScale: 0.58,
        shotDelayMs: 520,
        initialDelayMs: 320,
        bearingSpread: 1.2,
      ),
      resultCopy: WorldResultCopy(
        win: 'ACCESS GRANTED',
        lose: 'BREACH FAILED',
        draw: 'TIMEOUT',
        spectator: 'REMOTE VIEW',
        abort: 'LINK SEVERED',
      ),
    ),
    WorldProfile.arg: WorldStudioIdentity(
      profile: WorldProfile.arg,
      layout: WorldLayoutRhythm(
        screenPaddingH: 10,
        screenPaddingV: 10,
        sectionGap: 8,
        cardGap: 6,
        dialogPaddingH: 10,
        symmetric: false,
        contentAlign: Alignment.centerLeft,
        cardFloat: 0,
        hudEdgeInset: 4,
        galleryHeroHeight: 0.30,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 200,
        reverseTransitionMs: 160,
        dialogMs: 180,
        buttonMs: 60,
        staggerMs: 25,
        enterCurve: Curves.linear,
        exitCurve: Curves.easeIn,
        emphasisCurve: Curves.easeOut,
        sheetCurve: Curves.easeOut,
      ),
      microcopy: WorldMicrocopy(
        confirm: '了解',
        cancel: '中止',
        close: '閉じる',
        next: '次へ',
        back: '戻る',
        loading: '待機中…',
        gallerySelect: 'Deploy',
        coachNext: '次へ',
        coachDone: '前進',
      ),
      haptic: WorldHapticCharacter.click,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 20,
        sfxTailMs: 80,
        transitionBreathMs: 50,
        resultPauseMs: 200,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 24,
        zoomOffset: 0.3,
        orbitScale: 0.48,
        shotDelayMs: 720,
        initialDelayMs: 440,
        bearingSpread: 0.85,
      ),
      resultCopy: WorldResultCopy(
        win: 'MISSION CLEAR',
        lose: 'COMPROMISED',
        draw: 'STALEMATE',
        spectator: 'FIELD LOG',
        abort: 'EXTRACTION',
      ),
    ),
    WorldProfile.magical: WorldStudioIdentity(
      profile: WorldProfile.magical,
      layout: WorldLayoutRhythm(
        screenPaddingH: 20,
        screenPaddingV: 18,
        sectionGap: 18,
        cardGap: 14,
        dialogPaddingH: 18,
        symmetric: true,
        contentAlign: Alignment.center,
        cardFloat: 4,
        hudEdgeInset: 12,
        galleryHeroHeight: 0.36,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 480,
        reverseTransitionMs: 380,
        dialogMs: 360,
        buttonMs: 120,
        staggerMs: 70,
        enterCurve: Curves.easeInOutSine,
        exitCurve: Curves.easeInOutSine,
        emphasisCurve: Curves.easeOutBack,
        sheetCurve: Curves.easeInOutCubic,
      ),
      microcopy: WorldMicrocopy(
        confirm: '唱える',
        cancel: '解呪',
        close: '封印',
        next: '次へ',
        back: '戻る',
        loading: '詠唱中…',
        gallerySelect: 'Attune',
        coachNext: '次へ',
        coachDone: '目覚め',
      ),
      haptic: WorldHapticCharacter.soft,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 60,
        sfxTailMs: 140,
        transitionBreathMs: 100,
        resultPauseMs: 320,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 36,
        zoomOffset: 0.5,
        orbitScale: 0.6,
        shotDelayMs: 860,
        initialDelayMs: 500,
        bearingSpread: 1.0,
      ),
      resultCopy: WorldResultCopy(
        win: 'SPELL SEALED',
        lose: 'WARD BROKEN',
        draw: 'EQUILIBRIUM',
        spectator: 'SCRYING',
        abort: 'RITUAL END',
      ),
    ),
    WorldProfile.astronomy: WorldStudioIdentity(
      profile: WorldProfile.astronomy,
      layout: WorldLayoutRhythm(
        screenPaddingH: 28,
        screenPaddingV: 24,
        sectionGap: 24,
        cardGap: 16,
        dialogPaddingH: 24,
        symmetric: true,
        contentAlign: Alignment.center,
        cardFloat: 2,
        hudEdgeInset: 14,
        galleryHeroHeight: 0.40,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 560,
        reverseTransitionMs: 460,
        dialogMs: 420,
        buttonMs: 150,
        staggerMs: 100,
        enterCurve: Curves.easeInOutCubicEmphasized,
        exitCurve: Curves.easeInCubic,
        emphasisCurve: Curves.easeOutCubic,
        sheetCurve: Curves.easeInOut,
      ),
      microcopy: WorldMicrocopy(
        confirm: '送信',
        cancel: '保留',
        close: '閉じる',
        next: '次へ',
        back: '戻る',
        loading: '信号受信中…',
        gallerySelect: 'Tune In',
        coachNext: '次へ',
        coachDone: '出発',
      ),
      haptic: WorldHapticCharacter.lightLong,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 90,
        sfxTailMs: 200,
        transitionBreathMs: 140,
        resultPauseMs: 420,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 18,
        zoomOffset: -0.2,
        orbitScale: 0.72,
        shotDelayMs: 1100,
        initialDelayMs: 680,
        bearingSpread: 0.7,
      ),
      resultCopy: WorldResultCopy(
        win: 'SIGNAL HOME',
        lose: 'LOST IN VOID',
        draw: 'DRIFT',
        spectator: 'DEEP SKY',
        abort: 'LINK DOWN',
      ),
    ),
    WorldProfile.japaneseLuxury: WorldStudioIdentity(
      profile: WorldProfile.japaneseLuxury,
      layout: WorldLayoutRhythm(
        screenPaddingH: 32,
        screenPaddingV: 28,
        sectionGap: 28,
        cardGap: 20,
        dialogPaddingH: 28,
        symmetric: false,
        contentAlign: Alignment.centerLeft,
        cardFloat: 0,
        hudEdgeInset: 16,
        galleryHeroHeight: 0.42,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 620,
        reverseTransitionMs: 500,
        dialogMs: 460,
        buttonMs: 160,
        staggerMs: 110,
        enterCurve: Curves.easeInOutCubic,
        exitCurve: Curves.easeInOutCubic,
        emphasisCurve: Curves.easeOutCubic,
        sheetCurve: Curves.easeInOutQuart,
      ),
      microcopy: WorldMicrocopy(
        confirm: '整いました',
        cancel: 'いまはやめておく',
        close: '閉じる',
        next: 'つづける',
        back: '戻る',
        loading: '静かに準備中…',
        gallerySelect: 'この世界へ',
        coachNext: 'つぎへ',
        coachDone: 'はじめる',
      ),
      haptic: WorldHapticCharacter.soft,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 120,
        sfxTailMs: 240,
        transitionBreathMs: 160,
        resultPauseMs: 480,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 14,
        zoomOffset: -0.4,
        orbitScale: 0.65,
        shotDelayMs: 1200,
        initialDelayMs: 720,
        bearingSpread: 0.6,
      ),
      resultCopy: WorldResultCopy(
        win: '静寂の勝ち',
        lose: '影に沈む',
        draw: '余白のまま',
        spectator: '静観',
        abort: '席を立つ',
      ),
    ),
    WorldProfile.westernLuxury: WorldStudioIdentity(
      profile: WorldProfile.westernLuxury,
      layout: WorldLayoutRhythm(
        screenPaddingH: 24,
        screenPaddingV: 22,
        sectionGap: 20,
        cardGap: 16,
        dialogPaddingH: 24,
        symmetric: true,
        contentAlign: Alignment.center,
        cardFloat: 3,
        hudEdgeInset: 12,
        galleryHeroHeight: 0.38,
      ),
      motion: WorldMotionRhythm(
        transitionMs: 440,
        reverseTransitionMs: 360,
        dialogMs: 340,
        buttonMs: 110,
        staggerMs: 60,
        enterCurve: Curves.easeOutQuart,
        exitCurve: Curves.easeInOutQuart,
        emphasisCurve: Curves.easeOutCubic,
        sheetCurve: Curves.easeOutQuart,
      ),
      microcopy: WorldMicrocopy(
        confirm: '進める',
        cancel: '見送る',
        close: '閉じる',
        next: '次へ',
        back: '戻る',
        loading: 'お待ちください…',
        gallerySelect: 'Enter Hall',
        coachNext: '次へ',
        coachDone: '開廷',
      ),
      haptic: WorldHapticCharacter.refined,
      silence: WorldSilenceRhythm(
        sfxLeadMs: 70,
        sfxTailMs: 180,
        transitionBreathMs: 110,
        resultPauseMs: 360,
      ),
      camera: WorldMapCameraRhythm(
        tilt: 32,
        zoomOffset: 0.4,
        orbitScale: 0.55,
        shotDelayMs: 900,
        initialDelayMs: 560,
        bearingSpread: 0.9,
      ),
      resultCopy: WorldResultCopy(
        win: 'VERDICT',
        lose: 'DISMISSED',
        draw: 'ADJOURNED',
        spectator: 'GALLERY VIEW',
        abort: 'RECESS',
      ),
    ),
  };
}
